"""simplify detection_history

Revision ID: 35ff6e07846b
Revises: 6656c96403eb
Create Date: 2026-04-21 11:27:16.021096

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '35ff6e07846b'
down_revision: Union[str, Sequence[str], None] = '6656c96403eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema - remove message and stats columns to save storage."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('detection_history', 'message')
    op.drop_column('detection_history', 'stats')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema - restore message and stats columns."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('detection_history', sa.Column('message', sa.Text(), nullable=True))
    op.add_column('detection_history', sa.Column('stats', sa.JSON(), nullable=True))
    # ### end Alembic commands ###
