"""Add unified detection_history table

Revision ID: 6656c96403eb
Revises: ec95a448e13d
Create Date: 2026-04-20 15:03:25.690389

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6656c96403eb'
down_revision: Union[str, Sequence[str], None] = 'ec95a448e13d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('detection_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('report_id', sa.String(length=50), nullable=False),
    sa.Column('detection_type', sa.String(length=20), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('vehicle_count', sa.Integer(), nullable=True),
    sa.Column('processing_time', sa.String(length=50), nullable=True),
    sa.Column('confidence_threshold', sa.Float(), nullable=True),
    sa.Column('image_data', sa.Text(), nullable=True),
    sa.Column('video_path', sa.String(length=255), nullable=True),
    sa.Column('stats', sa.JSON(), nullable=True),
    sa.Column('breakdown', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('report_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('detection_history')
    # ### end Alembic commands ###
