"""add theme to user

Revision ID: add_theme_to_user
Revises: 35ff6e07846b
Create Date: 2026-04-27 12:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'add_theme_to_user'
down_revision: Union[str, Sequence[str], None] = '35ff6e07846b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema - add theme column to users table."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('theme', sa.String(length=10), nullable=True, server_default='light'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema - remove theme column from users table."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'theme')
    # ### end Alembic commands ###
