"""add password reset fields

Revision ID: add_password_reset_fields
Revises: add_theme_to_user
Create Date: 2026-04-27 12:30:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'add_password_reset_fields'
down_revision: Union[str, Sequence[str], None] = 'add_theme_to_user'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema - add password reset token fields."""
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    existing = {row[0] for row in conn.execute(sa.text("SELECT column_name FROM information_schema.columns WHERE table_name='users'")).fetchall()}
    if 'reset_token' not in existing:
        op.add_column('users', sa.Column('reset_token', sa.String(length=255), nullable=True))
    if 'reset_token_expires' not in existing:
        op.add_column('users', sa.Column('reset_token_expires', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema - remove password reset token fields."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'reset_token_expires')
    op.drop_column('users', 'reset_token')
    # ### end Alembic commands ###
